//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace plugin.collctr.ruckzuck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("plugin.collctr.ruckzuck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon096 {
            get {
                object obj = ResourceManager.GetObject("Icon096", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $SVC = New-WebServiceProxy -uri &apos;https://ruckzuck.azurewebsites.net/api/api.asmx&apos; -UseDefaultCredential $true
        ///$Product = &apos;xxx&apos;
        ///$ProductVersion = &apos;yyy&apos;
        ///$DTs = $SVC.getDeploymentTypes($Product, $ProductVersion)
        ///#$URL = &apos;internal URL&apos;
        ///
        ///Import-Module BitsTransfer
        ///
        ///foreach($DT in $DTs)
        ///{
        ///	if((Invoke-Expression -Command $DT.PSPreReq) -eq $true) 
        ///	{
        ///		if((Invoke-Expression -Command $DT.PSDetection) -ne $true)
        ///		{
        ///            $Folder =  join-path $env:TEMP $DT.ContentId
        ///            New-Item -ItemType [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PSInstall {
            get {
                return ResourceManager.GetString("PSInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $SVC = New-WebServiceProxy -uri &apos;https://ruckzuck.azurewebsites.net/api/api.asmx&apos; -Namespace RZ
        ///$token = &apos;&lt;token&gt;&apos;
        ///$SVC.SecuredWebServiceHeaderValue = New-Object RZ.SecuredWebServiceHeader -Prop (@{&quot;AuthenticatedToken&quot;=$token})
        ///
        /// [RZ.AddSoftware[]]$a = (Get-ItemProperty HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Where-Object &quot;Displayname&quot; -ne $null | Where-Object &quot;SystemComponent&quot; -ne 1 | Where-Object &quot;ParentDisplayName&quot; -eq $null | Select-Object DisplayName, DisplayVersio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PSUpdateCheck {
            get {
                return ResourceManager.GetString("PSUpdateCheck", resourceCulture);
            }
        }
    }
}
